### ISSUE TITLE
Uncaught TypeError Preventing Extension From Running

### ISSUE THREAD

**Issue by BennettRand** [JB4GDI/awsfaviconupdater#4]
```
Uncaught TypeError: document.URL.matchAll is not a function
    at faviconupdate.js:99
(anonymous) @ faviconupdate.js:99
```

Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by JB4GDI** [comment]
Thanks for the tip!  What page are you on when you see this?  I tried multiple computers and can't replicate, which makes me think it's either a URL with something weird going on, or there's a content blocker or extension that's also doing something strange.  Any more info would be appreciated thanks!

**Comment by samuel-massinon** [comment]
I have the same error, even in incognito with no other extensions.
It happens with all the AWS services I checked. 
Version 71.0.3578.98 (Official Build) (64-bit)
On Ubuntu

`matchAll` isn't a method for strings.
```javascript
test = "test"
// "test"
test.match
// ƒ match() { [native code] }
test.matchAll
//  undefined
```

**Comment by BennettRand** [comment]
`matchAll` is in the [ECMA-262](https://tc39.es/ecma262/#sec-string.prototype.matchall) draft and was just added in Chrome version 73. (And was recently added to Firefox version 67)

It's working now after I updated to 75.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#Browser_compatibility
